### ISSUE TITLE
I'm curious how you are using this

### ISSUE THREAD

**Issue by aplatti** [gerardroche/sublime-pine#4]
Hi, I'm curious if you are cutting and pasting your Pine Script code out of sublime text and into TradingView, or if you have some other way to execute the Pine Script code on trading view.  I would love to find a way to edit my scripts in an external editor.   Thanks!

**Comment by gerardroche** [comment]
I just copy and paste. I haven't used TradingView in a while. It was a little bit of a hassle copy and pasting the scripts, but I still found it easier to work on them in Sublime.
