### ISSUE TITLE
Packages location

### ISSUE THREAD

**Issue by glikar** [gerardroche/sublime-pine#5]
Thanks for the highlighter!
Looks like in Mint it wants the pine package in;/home/'user'/.var/app/com.sublimetext.three/config/sublime-text-3/Packages/User

**Comment by gerardroche** [comment]
The preferred method of installation is [Package Control](https://packagecontrol.io/packages/Pine).

`Ctrl/Command + Shift + P` to open the Command Palette

Select `Package Control: Install Package`

Search for `Pine`

Press `Enter`

Go to `Menu > Preferences > Color Scheme...` and select Pine.
