### ISSUE TITLE
Not usable anymore, maybe caused by change in Sublime Text engine

### ISSUE THREAD

**Issue by R3cycl0r** [gerardroche/sublime-pine#6]
There is no way to let these files integrate with Sublime Text 3 anymore, as it asks for 'sublime-packages' and not 'sublime-syntax' that are not contained in the documentation.

**Comment by gerardroche** [comment]
The `.sublime-syntax` syntax was introduced in build version 3103, the package will only support builds greater than 3102. See https://www.sublimetext.com/blog/articles/sublime-text-3-build-3103
